sysucc-master/sysucc/cccga/urls.py
from django.urls import path

from .views import (
    index, workflow, sampleqc,
    variation, download,
    querygene, query_sample, category,
    sampleinfo_ajax, querygene_vep_ajax,
    sampletab_ajax, sampletab,
    sampleinfo_export, sampleinfo_export_all
)


app_name = 'cccga'
urlpatterns = [
    path('', index, name='index'),
    path('workflow/', workflow, name='analysis_workflow'),
    path('sampleqc/', sampleqc, name='sample_qc'),
    path('sampletab/', sampletab, name='sample_tab'),
    path('ajax/sampletab/', sampletab_ajax, name='sample_table_ajax'),
    path('ajax/sampleinfo/', sampleinfo_ajax, name='sampleinfo_ajax'),
    path('ajax/sampleinfo/export/', sampleinfo_export, name='sampleinfo_export'),
    path('ajax/sampleinfo/exportall/', sampleinfo_export_all, name='sampleinfo_export_all'),
    path('variation/', variation, name='variation'),
    path('category/', category, name='category'),
    path('querygene/', querygene, name='querygene'),
    path('ajax/querygene/', querygene_vep_ajax, name='querygene_ajax'),
    path('querysample/', query_sample, name='query_sample'),
    path('download/', download, name='download')
]

sysucc-master/sysucc/cccga/forms.py
from django import forms


class QueryForm(forms.Form):
    QT = (
        ('Gene', 'Gene'),
        ('Sample', 'Sample')
    )
    query_type = forms.ChoiceField(choices=QT)
    query_content = forms.CharField(widget=forms.TextInput(attrs={'size': '40'}))

sysucc-master/sysucc/cccga/views.py
import csv
import json
import os
import re
import time

from django.conf import settings
from django.http import HttpResponse
from django.http import JsonResponse
from django.http import StreamingHttpResponse
from django.shortcuts import render
from django.utils.translation import ugettext_lazy as _
from django.views.decorators.csrf import csrf_exempt

from .models import (
    ProteinDomainsDB, Hgnc2PfamDB,
    SampleClinicInfo, TumorSampleQC, NormalSampleQC,
    VariationClassification, VariantType,
    SnvClass, GeneVariationClassification,
    SortedGeneVariationClassification
)
from .get_data import (
    index_data, variation_data,
    sampleinfo_data, category_data,
    sampletab_initialize, sampletab_data
)


# LANGUAGES = (
#     ('en-us', _('English')),
#     ('zh-hans', _('Chinese')),
# )
LANGUAGES = settings.LANGUAGES


# Create your views here.
def index(request):
    infos = index_data()

    return render(request, 'cccga/index.html', {'infos': infos, "LANGUAGES": LANGUAGES})


def workflow(request):
    return render(request, 'cccga/workflow.html', {"LANGUAGES": LANGUAGES})


def sampleqc(request):
    if request.method == 'POST':
        if request.POST.get('action') == 'search':
            kwargs = {}
            barcode = request.POST.get('barcode').strip()
            if barcode:
                kwargs['barcode'] = barcode.split('_')[0] + '_NT'
            pathological_stage = request.POST.get('patho-stage').strip()
            if pathological_stage:
                kwargs['pathological_stage'] = pathological_stage
            primary_location = request.POST.get('pri-loc').strip()
            if primary_location:
                kwargs['primary_location'] = primary_location
            detailed_site = request.POST.get('det-site').strip()
            if detailed_site:
                kwargs['detailed_site'] = detailed_site
            infos = sampleinfo_data(**kwargs)
        elif request.POST.get('action') == 'reset':
            infos = sampleinfo_data()
    else:
        infos = sampleinfo_data()

    return render(request, 'cccga/sampleqc.html', {'infos': infos, "LANGUAGES": LANGUAGES})


def sampletab(request):
    infos = sampletab_initialize()

    return render(request, 'cccga/sampleqc.html', {'infos': infos, "LANGUAGES": LANGUAGES})


def sampletab_ajax(request):
    if request.method == 'POST':
        reqd = request.POST
        # print(reqd)
        # print(len(reqd.get('order')))
        # filter
        kwargs = {}
        barcode = reqd.get('columns[1][search][value]').strip()
        if barcode:
            kwargs['barcode'] = barcode.split('_')[0] + '_NT'
        pathological_stage = reqd.get('columns[5][search][value]').strip()
        if pathological_stage:
            kwargs['pathological_stage'] = pathological_stage
        primary_location = reqd.get('columns[6][search][value]').strip()
        if primary_location:
            kwargs['primary_location'] = primary_location
        detailed_site = reqd.get('columns[7][search][value]').strip()
        if detailed_site:
            kwargs['detailed_site'] = detailed_site
        # print(kwargs)
        # order
        order = []
        order_column = reqd.get('order[0][column]', None)  # 注意多值排序
        if order_column is not None:
            order_field = reqd.get('columns[{}][data]'.format(order_column))
            order_way = reqd.get('order[0][dir]')  # 注意多值排序
            if order_way == 'asc':
                order.append('{}'.format(order_field))
            if order_way == 'desc':
                order.append('-{}'.format(order_field))
        else:
            # 默认排序
            order_field = reqd.get('columns[5][data]')
            order = ['{}'.format(order_field)]
        # page
        page_length = int(reqd.get('length', '25'))
        page_start = int(reqd.get('start', '0'))
        # get data
        sampleinfos, total_length = sampletab_data(page_start, page_length, tuple(order), **kwargs)
        infos = {"iTotalRecords": page_length}
        infos["sampleinfos"] = sampleinfos
        infos["iTotalDisplayRecords"] = total_length
    else:
        return HttpResponse(f'Invalid Request.')

    return JsonResponse(infos)


def sampleinfo_ajax(request):
    if request.method == 'GET':
        infotype = request.GET.get('infoType')
        sampleinfo = {}
        if infotype == 'clinic':
            barcode = request.GET.get('barcode')
            obj = SampleClinicInfo.objects.get(barcode=barcode)
            sampleinfo['barcode'] = obj.barcode
            sampleinfo['gender'] = obj.gender
            sampleinfo['diagnosis_age'] = obj.diagnosis_age
            sampleinfo['surgery_date'] = obj.surgery_date
            sampleinfo['pathological_grade'] = obj.pathological_grade
            sampleinfo['pathological_stage'] = obj.pathological_stage
            sampleinfo['primary_location'] = obj.primary_location
            sampleinfo['detailed_site'] = obj.detailed_site
            sampleinfo['metastasis'] = obj.metastasis
            sampleinfo['time_os'] = obj.time_os
            sampleinfo['ajcc_T_stage'] = obj.ajcc_T_stage
            sampleinfo['ajcc_N_stage'] = obj.ajcc_N_stage
        elif infotype == 'tsampleqc':
            barcode = request.GET.get('barcode')
            obj = TumorSampleQC.objects.get(tsampleid=barcode)
            sampleinfo['tsampleid'] = obj.tsampleid
            sampleinfo['lib_type'] = obj.lib_type
            sampleinfo['rawsize'] = obj.rawsize
            sampleinfo['duplicate_rate'] = obj.duplicate_rate
            sampleinfo['foebot'] = obj.foebot
            sampleinfo['asdot'] = obj.asdot
            sampleinfo['cotr'] = obj.cotr
        elif infotype == 'nsampleqc':
            barcode = request.GET.get('barcode')
            obj = NormalSampleQC.objects.get(nsampleid=barcode)
            sampleinfo['nsampleid'] = obj.nsampleid
            sampleinfo['lib_type'] = obj.lib_type
            sampleinfo['rawsize'] = obj.rawsize
            sampleinfo['duplicate_rate'] = obj.duplicate_rate
            sampleinfo['foebot'] = obj.foebot
            sampleinfo['asdot'] = obj.asdot
            sampleinfo['cotr'] = obj.cotr

    return JsonResponse(sampleinfo)


class Echo:
    def write(self, value):
        return value


@csrf_exempt
def sampleinfo_export(request):
    if request.method == 'POST':
        contents = request.POST.get('contents')
        contents = contents.split(',')
        samples = request.POST.get('samples')
        samples = samples.split(',')
        infos = []
        time_stamp = time.strftime("%Y-%m-%d_%H%M%S", time.localtime())
        for sample in samples:
            sampleinfo = {}
            barcode = sample
            tsampleid, nsampleid = '', ''
            if 'clinic' in contents:
                try:
                    obj = SampleClinicInfo.objects.get(barcode=barcode)
                    tsampleid, nsampleid = obj.tsampleid, obj.nsampleid
                except SampleClinicInfo.DoesNotExist:
                    obj = ''
                    tsampleid, nsampleid = '', ''
                sampleinfo['barcode'] = obj.barcode if obj else ''
                sampleinfo['gender'] = obj.gender if obj else ''
                sampleinfo['diagnosis_age'] = obj.diagnosis_age if obj else ''
                sampleinfo['surgery_date'] = obj.surgery_date.strftime('%Y-%m-%d') if (obj and obj.surgery_date) else ''
                sampleinfo['pathological_grade'] = obj.pathological_grade if obj else ''
                sampleinfo['pathological_stage'] = obj.pathological_stage if obj else ''
                sampleinfo['primary_tumor_location'] = obj.primary_location if obj else ''
                sampleinfo['detailed_tumor_site'] = obj.detailed_site if obj else ''
                sampleinfo['metastasis_at_diagnosis'] = obj.metastasis if obj else ''
                sampleinfo['time_from_diagnosis_to_death'] = obj.time_os if obj else ''
                sampleinfo['ajcc_T_stage'] = obj.ajcc_T_stage if obj else ''
                sampleinfo['ajcc_N_stage'] = obj.ajcc_N_stage if obj else ''
            if 'tumor' in contents:
                if not tsampleid:
                    try:
                        obj = SampleClinicInfo.objects.get(barcode=barcode)
                        tsampleid = obj.tsampleid
                    except SampleClinicInfo.DoesNotExist:
                        tsampleid = ''
                try:
                    obj = TumorSampleQC.objects.get(tsampleid=tsampleid)
                except TumorSampleQC.DoesNotExist:
                    obj = ''
                sampleinfo['tumor_sampleid'] = obj.tsampleid if obj else ''
                sampleinfo['tumor_library_type'] = obj.lib_type if obj else ''
                sampleinfo['tumor_raw_base_number(G)'] = obj.rawsize if obj else ''
                sampleinfo['tumor_duplicate_rate(%)'] = obj.duplicate_rate if obj else ''
                sampleinfo['tumor_fraction_of_effective_bases_on_target(%)'] = obj.foebot if obj else ''
                sampleinfo['tumor_average_sequencing_depth_on_target'] = obj.asdot if obj else ''
                sampleinfo['tumor_coverage_of_target_region(%)'] = obj.cotr if obj else ''
            if 'normal' in contents:
                if not nsampleid:
                    try:
                        obj = SampleClinicInfo.objects.get(barcode=barcode)
                        nsampleid = obj.nsampleid
                    except SampleClinicInfo.DoesNotExist:
                        tsampleid = ''
                try:
                    obj = NormalSampleQC.objects.get(nsampleid=nsampleid)
                except NormalSampleQC.DoesNotExist:
                    obj = ''
                sampleinfo['normal_sampleid'] = obj.nsampleid if obj else ''
                sampleinfo['normal_library_type'] = obj.lib_type if obj else ''
                sampleinfo['normal_raw_base_number(G)'] = obj.rawsize if obj else ''

sysucc-master/sysucc/cccga/templates/cccga/base.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}The ChangKang Project{% endblock %}</title>
    <meta name="description" content="">
    <meta name="keyword" content="Chinese Colorectal Cancer Genome Atlas, CCCGA">
    <meta name="author" content="">
    <link rel="icon" href="https://www.haplox.cn/favicon.ico">

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{% static 'bootstrap-3.3.7-dist/css/bootstrap.min.css' %}">
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'bootstrap-3.3.7-dist/js/bootstrap.min.js' %}"></script>
    <!-- Custom styles for this template -->
    <link href="{% static 'cccga/base.css' %}" rel="stylesheet">
    <style type="text/css">
      body {
        min-height: 1000px;
        padding-top: 0px;
      }
      .log-header {
        border-left: 0px solid #FF6100;
        padding-top: 40px;
        padding-bottom: 40px;
        margin-top: 0px;
        background-color: #eee;
        font-size: 40px;
        font-weight: bold;
        text-align: center;
        color: black;
      }
      .navbar {
        min-height: 30px;
        margin-bottom: 10px;
        background-color: #3565ff; /*#3aa5c8;#3433e3;#3565ff;*/
        /*border-color: #3433e3;*/
        border-style: none;
        border-radius: 0px 0px 4px 4px;
      }
      .navbar-nav {
        padding-top: 0px;
        padding-bottom: 0px;
      }
      .navbar-default .navbar-nav > li > a {
        color: #fff;
        margin-right: 20px;
        background-color: #3565ff; /*#3aa5c8;#3433e3;*/
      }
      .navbar-header {
        background-color: #3565ff; /*#3aa5c8;#3433e3;*/
        min-height: 30px;
      }
      .navbar-toggle {
        padding: 5px 10px;
        margin-top: 0px;
        margin-right: 15px;
        margin-bottom: 0px;
      }
      .navbar-default .navbar-toggle {
        border-color: #3aa5c8;
      }
      .navbar-default .navbar-toggle:hover,
      .navbar-default .navbar-toggle:focus {
        background-color: #3565ff; /*#3aa5c8;#3433e3;*/
      }
      .navbar-default .navbar-toggle .icon-bar {
        background-color: #fff;
      }
    </style>
    <script>
      function selectLanguage(obj) {
          str="/i18n/setlang/";
          myform = document.getElementById('setLanguage');
          myform.method = "POST";
          myform.action = str;
          myform.submit();
      }
    </script>
    {% block extrastyle %}{% endblock %}
  </head>

  <body>
    <div class="container">
      <div class="row">
        <div class="col-xs-12">
          <!--
          <div class="log-header">
            <span>{# Chinese Colorectal Cancer Genome Atlas #}</span>
          </div>-->
          <div>
            <img src="{% static 'cccga/the_ck_proj.jpg' %}">
          </div>
        </div>
      </div>

      {% block navbar %}
      <!-- Fixed navbar -->
      <nav class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#target-menu" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div id="target-menu" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-left">
            <li class="{% block index_active %}{% endblock %}">
                <a href="{% url 'cccga:index' %}"><span class="glyphicon glyphicon-home"></span><b> {% trans "Home" %}</b></a>
            </li>
            <li class="{% block workflow_active %}{% endblock %}">
                <a href="{% url 'cccga:analysis_workflow' %}"><span class="glyphicon glyphicon-tasks"></span><b> {% trans "Analysis Workflow" %}</b></a>
            </li>
            <li class="{% block qc_active %}{% endblock %}">
                <a href="{% url 'cccga:sample_tab' %}"><span class="glyphicon glyphicon-list"></span><b> {% trans "Sample Information" %}</b></a>
            </li>
            <li class="{% block variation_active %}{% endblock %}">
              <a href="{% url 'cccga:variation' %}"><span class="glyphicon glyphicon-stats"></span><b> {% trans "Variation" %}</b></a>
            </li>
            <li class="{% block download_active %}{% endblock %}">
              <a href="{% url 'cccga:download' %}"><span class="glyphicon glyphicon-download-alt"></span><b> {% trans "Download" %}</b></a>
            </li>
          </ul>
        </div><!--/.nav-collapse -->
        </div>
      </nav>
      </div>
      {% endblock %}
    </div>

    {% block content %}{% endblock %}

    {% block footer %}
    <div class="container">
      <div class="row">
        <div class="col-xs-12">
          <br />
          <footer>
            <div class="gray-line"></div>
            <div class="white-line"></div>
            <div class="foot">
              <div class="foot-text">
                <form name="setLanguage" id="setLanguage" method='post'>
                    {% csrf_token %}
                    <span style="color:white;">
                      Copyright &copy; SYSUCC, {% trans "All Rights Reserved" %}.
                    </span>
                    <!--
                    <select id="language" name="language" onchange="selectLanguage(this)">
                        <option value="1">{% trans "Languages" %}</option>
                        {% for lang in LANGUAGES %}
                        <option value="{{ lang.0 }}">{{ lang.1 }}</option>
                        {% endfor %}
                    </select>
                    -->
                    <br />
                    <script>
                      var cnzz_protocol = (("https:" == document.location.protocol) ? "https://" : "http://");
                      document.write(unescape("%3Cspan id='cnzz_stat_icon_1280940671'%3E%3C/span%3E%3Cscript src='" + cnzz_protocol + "s4.cnzz.com/z_stat.php%3Fid%3D1280940671%26show%3Dpic1' type='text/javascript'%3E%3C/script%3E"));
                    </script>
                    <a href="https://beian.miit.gov.cn" target="_blank">粤ICP备14082947号</a>
                </form>
              </div>
            </div>
          </footer>
        </div>
      </div>
    </div>
    {% endblock %}
  </body>
</html>

sysucc-master/sysucc/cccga/templates/cccga/base_variation.html
{% extends "cccga/base.html" %}
{% load static %}
{% load i18n %}

{% block extrastyle %}
<!-- 引入 ECharts 文件 -->
<!-- <script src="https://cdn.staticfile.org/echarts/4.8.0/echarts.min.js"></script> -->
<script src="{% static 'js/echarts.min.js' %}"></script>
<script src="{% static 'js/d3.v3.min.js' %}" charset="utf-8"></script>
{% endblock %}

{% block variation_active %}active{% endblock %}
{% block content %}
<div class="container">
  <div class="row">
    <div class="col-xs-3">
      {% block content-sidebar %}
    	<div class="panel panel-info">
        <div class="panel-heading">
          <h3 class="panel-title">&nbsp;<span class="glyphicon glyphicon-eye-open"></span> &nbsp;{% trans "Variation Viewer" %}</h3>
        </div>
          <a href="{% url 'cccga:variation' %}" class="list-group-item {% block varall_active %}{% endblock %}"><strong>&nbsp;<span class="glyphicon glyphicon-list"></span> &nbsp;{% trans "Overview" %}</strong></a>
          <a href="{% url 'cccga:category' %}" class="list-group-item {% block varcategory_active %}{% endblock %}"><strong>&nbsp;<span class="glyphicon glyphicon-paperclip"></span> &nbsp;{% trans "Cohort Study" %}</strong></a>
          <!--
          <a href="{% url 'cccga:query_sample' %}" class="list-group-item"><strong>&nbsp;<span class="glyphicon glyphicon-search"></span> &nbsp;Search Samples</strong></a> -->
          <a href="{% url 'cccga:querygene' %}" class="list-group-item {% block varquery_active %}{% endblock %}"><strong>&nbsp;<span class="glyphicon glyphicon-search"></span> &nbsp;{% trans "Search Gene" %}</strong></a>
      </div>
      <div style="height: 600px"></div>
      {% endblock %}
    </div>
    <div class="col-xs-9">
      {% block content-detail %}
      {% endblock %}
    </div>
  </div>
</div>
{% endblock %}

sysucc-master/sysucc/cccga/templates/cccga/cnv.html
{% extends "cccga/base.html" %}
{% load static %}

{% block extrastyle %}
<link rel="stylesheet" type="text/css" href="{% static 'DataTables/datatables.min.css' %}"/>
<style type="text/css">
div.dataTables_wrapper {
        /* width: 1900px; */
        /* margin: 0 auto; */
    }
</style>
<script type="text/javascript" src="{% static 'DataTables/datatables.min.js' %}"></script>
<script>
    $(document).ready(function() {
        $('#cnv').DataTable({
        	"scrollY": 250,
            "scrollX": true,
            searching: false,
            "ordering": false,
            "aLengthMenu" : [10, 20, 50, 100], //更改显示记录数选项
            "iDisplayLength" : 20, //默认显示的记录数
        });
    } );
</script>
<script src="{% static 'js/d3.v3.min.js' %}" charset="utf-8"></script>

{% endblock %}

{% block variation_active %}active{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
    	<div class="col-xs-3">
    		<div class="panel panel-info">
                <div class="panel-heading">
                  <h3 class="panel-title">&nbsp;<span class="glyphicon glyphicon-eye-open"></span> &nbsp;Variation</h3>
                </div>
				<a href="{% url 'cccga:variation' %}" class="list-group-item"><strong>&nbsp;<span class="glyphicon glyphicon-list"></span> &nbsp;ALL</strong></a>
                <a href="{% url 'cccga:snv' %}" class="list-group-item"><strong>&nbsp;Somatic SNV</strong></a>
                <a href="{% url 'cccga:cnv' %}" class="list-group-item active"><strong>&nbsp;Somatic CNV</strong></a>
                <a href="{% url 'cccga:query_sample' %}" class="list-group-item"><strong>&nbsp;<span class="glyphicon glyphicon-search"></span> &nbsp;Search Samples</strong></a>
                <a href="{% url 'cccga:query_gene' %}" class="list-group-item"><strong>&nbsp;<span class="glyphicon glyphicon-search"></span> &nbsp;Search Gene</strong></a>
            </div>
    	</div>
    	<div class="col-xs-9">
    		<div class="row">
    			<div class="row searchbg">
                    <div class="col-sm-1">
                       <!-- <span class="tt pull-right"><font color="#696969">CPGEA</font> &nbsp;&nbsp;</span>-->
                    </div>
                    <div class="col-sm-2 mtop13">
                        <select class="form-control height36 new-form-control1" name="query_type" id="query_type">
                            <option value="op_gene">&nbsp;&nbsp;Gene</option>
                            <option value="op_sample">&nbsp;&nbsp;Sample</option>
                        </select>
                    </div>
                    <div class="col-sm-6 mtop13">
                        <input type="text" class="form-control height36 new-form-control1" name="valuex" id="valuex">
                    </div>
                    <div class="col-sm-3">
                        <button type="button" name="submit" class="btn btn-green button_query" style="background-color:#C0C0C0">Search</button>
                    </div>
                </div>
    		</div>
    		<hr>
    		<!--<div class="row">
                <div id="containerx"></div>
            </div>
            <hr>-->
            <div class="row">
                <div class="col-md-1"></div>
                <table>                                 
                    <tr>
                        <td><font style="color:#473C8B;font-size:110%;font-weight:600;"> Amplification Frequency: &nbsp;&nbsp;0.00%</font></td>
                    </tr>
                    <tr>
                        <td><font style="color:#473C8B;font-size:110%;font-weight:600;"> Deletion Frequency: &nbsp;&nbsp; 0.00%</font></td>
                    </tr>
                </table>
            </div>
    		<hr>
    		{# table content #}
            <div class="row">
                <div class="col-xs-12 col-md-12">
                    <table id="cnv" class="table table-bordered table-hover display" style="width:100%">
                        <thead>
                            <tr style="background-color: #eee">
                                <th>Hugo_Symbol</th>
                                <th>Entrez_Gene_Id</th>
                                <th>Tumor_Sample_Barcode</th>
                                <th>CNV_Type</th>
                                <th>Chromosome</th>
                                <th>Start_position</th>
                                <th>End_Position</th>
                                <th>cytoBand</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for snv in snvs %}
                            <tr>
                                <td>{{ snv.symbol }}</td>
                                <td>{{ snv.gene_id }}</td>
                                <td>{{ snv.tumor_sampleid }}</td>
                                <td>{{ snv.aachange }}</td>
                                <td>{{ snv.vari_type }}</td>
                                <td>{{ snv.chromos }}</td>
                                <td>{{ snv.spo }}</td>
                                <td>{{ snv.epo }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    <br>
                </div>
            </div>
    	</div>
    </div>
</div>
<script>
var x_list = [0,393];
var assign_width = 700;
var assign_height = 160;
var padding = {top: 0, right: 60, bottom: 30, left: 13};
var width = assign_width;
var height = assign_height;
var svg = d3.select("#containerx")
            .append('svg')
            .attr('width', width)
            .attr('height', height);
</script>
{% endblock %}

sysucc-master/sysucc/cccga/templates/cccga/download.html
{% extends "cccga/base.html" %}

{% block download_active %}active{% endblock %}
{% block content %}
<div class="container">
	<div class="row">


		<div class="col-xs-12">
          <div class="panel panel-info">
            <div class="panel-heading">
              <div class="panel-title" style="font-weight: bold;">Download the data of somatic mutations</div>
            </div>
            <div class="panel-body" style="height:720px;">
              <p style="font-size:16px;margin:50px;">
				  MAF File: <a href="https://changkang.hapyun.com/static/download/SYSUCC_CRC_Mutation_withSilent.zip" target="_blank">SYSUCC_CRC_Mutation_withSilent.zip</a>
			  </p>
              <br>
            </div>
          </div>
        </div>


	</div>
</div>
{% endblock %}